Repository IlyaBat9/manpower, pull requests merged in 2019-07, with the labels that each got.

#4 Удалён гитигнор дубль, убрана лишняя строка в другом
  .gitignore
  manpower-site/.gitignore
Labels: enhancement

#5 Delete idea folder
  .idea/.gitignore
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/manpower.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
Labels: bug

#7 Main page template blocking
  manpower-site/manpower-site/settings.py
  manpower-site/static/css/main.css
  manpower-site/static/fonts/PTRootUI_Bold.ttf
  manpower-site/static/fonts/PTRootUI_Regular.ttf
  manpower-site/static/js/main.js
  manpower-site/templates/manpower-site/home.html
Labels: good first issue

#8 Add login page + little bit of forntend rework
  manpower-site/main/urls.py
  manpower-site/main/views.py
  manpower-site/manpower-site/settings.py
  manpower-site/static/css/main.css
  manpower-site/templates/manpower-site/home.html
  manpower-site/templates/manpower-site/login-landing.html
Labels: enhancement
